### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" :"Nimz",
  "email" :"nimz@gmail.com",
  "address" :"1234 main street",
  "dateOfBirth" :"2000-01-01",
  "registeredDate" :"2020-09-09"
}