### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" :"Fixed Name and mail",
  "email" :"newmail@gmail.com",
  "address" :"4444 main street",
  "dateOfBirth" :"2000-01-01",
  "registeredDate" :"2020-09-09"
}