

PUT http://localhost:4000/patients/909e6b56-3721-425d-97ff-a1164bbb04b2
Content-Type: application/json

{

  "name": "John Doe Updated new",
  "email": "jj@gmail.com",
  "address": "123 Main St, Springfield",
  "dateOfBirth": "1985-06-15"
}